var express = require('express');
var app = express();
var mongoose = require('mongoose');
var bodyParser = require('body-parser');
var path = require('path');
app.use(bodyParser.json());
app.use(express.static(__dirname + "/public/dist/public"));
mongoose.Promise = global.Promise;
require('./models/product.js').product();
require('./config/routes.js')(app);
app.listen(8000, function(){});